version: '3'

services:
  lap:
    image: fauria/lap:latest
    restart: always
    ports:
      - '${PORTBASE}80:80'
    volumes:
      - html:/var/www/html

  service:
    build: ./service
    ports: 
      - "${PORTBASE}88:80"
    
volumes:
  html: